# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "maven" # See documentation for possible values
    directory: "/" # Location of package manifests
    exclude-paths:
      - "org.coreasm.config/**"
      - "org.coreasm.eclipse/**"
      - "org.coreasm.eclipse.feature/**"
      - "org.coreasm.eclipse.parent/**"
      - "org.coreasm.eclipse.repository/**"
      - "org.coreasm.engine/**"
      - "org.coreasm.ui.carma/**"
      - "org.coreasm.util/**"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      logging:
        patterns:
          - "ch.qos.logback:*"
          - "org.slf4j:*"
      maven-plugins:
        patterns:
          - "org.apache.maven.plugins:*"
          - "org.sonatype.plugins:*"
          - "*-maven-plugin"
          - "maven-*-plugin"
          - "org.apache.maven.scm:maven-scm-provider-gitexe"
          - "org.apache.maven.shared:maven-dependency-analyzer"
          - "com.puppycrawl.tools:checkstyle"
    ignore:
      - dependency-name: "org.eclipse.tycho:*"
        versions: [ ">=4.0.0" ] # requires newer maven version than available on Debian 12 Bookworm (current stable)
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
