<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<artifactId>org.coreasm.eclipse.parent</artifactId>
	<name>CoreASM Eclipse Parent Project</name>

	<parent>
		<groupId>de.athalis.coreasm</groupId>
		<artifactId>coreasm-parent</artifactId>
		<version>${revision}</version>
	</parent>

	<packaging>pom</packaging>

	<modules>
		<module>../org.coreasm.eclipse</module>
		<module>../org.coreasm.eclipse.feature</module>
		<module>../org.coreasm.eclipse.repository</module>
	</modules>

	<build>
		<plugins>

			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-versions-plugin</artifactId>
			</plugin>

			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-maven-plugin</artifactId>
				<extensions>true</extensions>
			</plugin>

			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>target-platform-configuration</artifactId>
				<configuration>
					<pomDependencies>consider</pomDependencies>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<phase>process-resources</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
						<configuration>
							<excludeTransitive>true</excludeTransitive>
							<excludeGroupIds>*</excludeGroupIds>
							<includeGroupIds>de.athalis.coreasm</includeGroupIds>
							<stripVersion>true</stripVersion>
							<outputDirectory>${project.build.directory}/lib/</outputDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>

	<repositories>
		<repository>
			<id>eclipse version</id>
			<url>${eclipse-repo.url}</url>
			<layout>p2</layout>
		</repository>
	</repositories>
</project>
